openapi: 3.0.4
info:
  title: Nintendo Music Compilations v1
  version: 0.0.1

paths:
  /creator/{id}:
    get:
      summary: Gets a creator by ID.
      operationId: getCreatorByID
      parameters:
        - name: id
          in: path
          description: Compilation ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful query
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /compilation/:
    post:
      summary: Creates a compilation
      operationId: createCompilation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                creatorID:
                  type: integer
                userDefinedTrackIDs:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      position:
                        type: integer
      responses:
        "200":
          description: Successful creation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Compilation"
    get:
      summary: Lists all compilations
      operationId: filterCompilations
      responses:
        "200":
          description: Successful listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Compilations"
  /compilation/{id}:
    get:
      summary: Gets a compilation by ID.
      operationId: getCompilationByID
      parameters:
        - name: id
          in: path
          description: Compilation ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successfuly query
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Compilation"
    put:
      summary: Updates a compilation by ID.
      operationId: putCompilationByID
      parameters:
        - name: id
          in: path
          description: Compilation ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                creatorID:
                  type: integer
                visibility:
                  $ref: "#/components/schemas/CompilationVisibility"
                userDefinedTracks:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      position:
                        type: integer
                compilationTracks:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      position:
                        type: integer
      responses:
        "200":
          description: Successfuly query
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Compilation"
  /userDefined/album:
    get:
      operationId: filterUserDefinedAlbums
      parameters:
        - name: name
          in: query
          description: The name of the album
          required: false
          schema:
            type: string
          example: "Animal Crossing: Wild World - K.K.'s Choice Mix!"
      responses:
        "200":
          description: Successful listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDefinedAlbums"
    post:
      operationId: createUserDefinedAlbum
      parameters:
        - name: name
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Successful album creation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDefinedAlbum"
  /userDefined/album/{id}/track:
    get:
      operationId: filterUserDefinedTracksByAlbumID
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: integer
        - name: title
          in: query
          description: The title of the track
          required: false
          schema:
            type: string
          example: "Overture"
      responses:
        "200":
          description: Successful listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDefinedTracks"
  /userDefined/track/{id}:
    patch:
      operationId: updateUserDefinedTrack
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nintendoMusicTrackId:
                  type: integer
      responses:
        "200":
          description: Successful track update
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDefinedTrack"
  /userDefined/track:
    post:
      operationId: createUserDefinedTrack
      parameters:
        - name: userDefinedAlbumId
          in: query
          schema:
            type: integer
        - name: title
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Successful track creation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDefinedTrack"
    get:
      operationId: filterUserDefinedTracks
      parameters:
        - name: title
          in: query
          description: The title of the track
          required: false
          schema:
            type: string
          example: "Title (First Snow Mix)"
        - name: isConnectedToNintendoMusicTrack
          in: query
          description: Is the UserDefined track connected to a NintendoMusicTrack?
          required: false
          schema:
            type: boolean
          example: false
      responses:
        "200":
          description: Successful listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDefinedTracks"
  /creator:
    post:
      operationId: createCreator
      parameters:
        - name: name
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Successful creator creation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    get:
      operationId: filterCreators
      parameters:
        - name: creatorId
          in: query
          description: The ID of the creator
          required: false
          schema:
            type: integer
          example: 1
        - name: username
          in: query
          description: The username of the creator
          required: false
          schema:
            type: string
          example: "Ezonater"
      responses:
        "200":
          description: Successful listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDefinedTracks"
  /creator/compilation:
    get:
      operationId: getCompilationForAuthenticatedUser
      responses:
        "200":
          description: Successful listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Compilations"
  /nintendoMusic/album:
    get:
      operationId: filterNintendoMusicAlbums
      parameters:
        - name: name
          in: query
          description: The name of the album
          required: false
          schema:
            type: string
          example: "Super Mario Odyssey"
      responses:
        "200":
          description: Successful listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NintendoMusicAlbums"
    post:
      operationId: createNintendoMusicAlbum
      parameters:
        - name: name
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Successful album creation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NintendoMusicAlbum"
  /nintendoMusic/album/{id}:
    get:
      summary: Gets a nintendo album by ID.
      operationId: getNintendoMusicAlbumByID
      parameters:
        - name: id
          in: path
          description: album ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successfuly query
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NintendoMusicAlbumWithTracks"
  /nintendoMusic/album/{id}/track:
    get:
      summary: Lists nintendo music tracks by album ID.
      operationId: filterNintendoMusicTracksByAlbumID
      parameters:
        - name: id
          in: path
          description: album ID
          required: true
          schema:
            type: integer
            format: int64
        - name: title
          in: query
          description: The title of the track
          required: false
          schema:
            type: string
          example: "Title Screen"
      responses:
        "200":
          description: Successfuly query
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NintendoMusicTracks"
  /nintendoMusic/track:
    get:
      operationId: filterNintendoMusicTracks
      parameters:
        - name: title
          in: query
          description: The title of the track
          required: false
          schema:
            type: string
          example: "Title Screen"
      responses:
        "200":
          description: Successful listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NintendoMusicTracksWithAlbum"
    post:
      operationId: createNintendoMusicTrack
      parameters:
        - name: nintendoMusicAlbumId
          in: query
          schema:
            type: integer
        - name: title
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Successful track creation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NintendoMusicTrack"
  /user/login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Successful login
  /user/authenticated:
    get:
      responses:
        "200":
          description: Successful login
  /user/session:
    get:
      operationId: getUserSession
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /compilation/{compilationId}/track/{trackId}:
    patch:
      operationId: updateCompilationTrack
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                addedToNMLPlaylist:
                  type: boolean
      parameters:
        - name: compilationId
          in: path
          description: compilation ID
          required: true
          schema:
            type: integer
            format: int64
        - name: trackId
          in: path
          description: track ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful update

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        avatarURL:
          type: string
        compilations:
          $ref: "#/components/schemas/Compilations"
    Compilations:
      type: array
      items:
        $ref: "#/components/schemas/Compilation"
    Compilation:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        thumbnailURL:
          type: string
        youtubeURL:
          type: string
        nintendoMusicURL:
          type: string
        creatorId:
          type: integer
        creator:
          $ref: "#/components/schemas/User"
        visibility:
          $ref: "#/components/schemas/CompilationVisibility"
        compilationTracks:
          $ref: "#/components/schemas/CompilationTracks"
    CompilationVisibility:
      type: string
      enum: [PRIVATE, PUBLIC]
    CompilationTracks:
      type: array
      items:
        $ref: "#/components/schemas/CompilationTrack"
    CompilationTrack:
      type: object
      properties:
        id:
          type: integer
        position:
          type: integer
        addedToNMLPlaylist:
          type: boolean
        userDefinedTrack:
          $ref: "#/components/schemas/UserDefinedTrack"
    UserDefinedAlbums:
      type: array
      items:
        $ref: "#/components/schemas/UserDefinedAlbum"
    UserDefinedAlbum:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    UserDefinedTracks:
      type: array
      items:
        $ref: "#/components/schemas/UserDefinedTrack"
    UserDefinedTrack:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        duration:
          type: number
        userDefinedAlbumId:
          type: number
        userDefinedAlbum:
          $ref: "#/components/schemas/UserDefinedAlbum"
        nintendoMusicLibraryTrackId:
          type: integer
        nintendoMusicLibraryTrack:
          $ref: "#/components/schemas/NintendoMusicTrack"
        spotifyGameTrackId:
          type: integer
    NintendoMusicAlbum:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    NintendoMusicAlbums:
      type: array
      items:
        $ref: "#/components/schemas/NintendoMusicAlbum"
    NintendoMusicAlbumWithTracks:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        tracks:
          $ref: "#/components/schemas/NintendoMusicTracks"
    NintendoMusicTrack:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
    NintendoMusicTracks:
      type: array
      items:
        $ref: "#/components/schemas/NintendoMusicTrack"
    NintendoMusicTrackWithAlbum:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        nintendoMusicLibraryGameAlbum:
          $ref: "#/components/schemas/NintendoMusicAlbum"
    NintendoMusicTracksWithAlbum:
      type: array
      items:
        $ref: "#/components/schemas/NintendoMusicTrackWithAlbum"
